
// <copyright file="PostOperationcrd9a_carCreate.cs" company="">
// Copyright (c) 2021 All Rights Reserved
// </copyright>
// <author></author>
// <date>10/15/2021 3:22:31 PM</date>
// <summary>Implements the PostOperationcrd9a_carCreate Plugin.</summary>
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
// </auto-generated>

using System;
using System.ServiceModel;
using Microsoft.Xrm.Sdk;

namespace CreateTaskWhenEntityCreated.CreateTaskWhenEntityCreated
{

    /// <summary>
    /// PostOperationcrd9a_carCreate Plugin.
    /// </summary>    
    public class PostOperationcrd9a_carCreate: PluginBase
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PostOperationcrd9a_carCreate"/> class.
        /// </summary>
        /// <param name="unsecure">Contains public (unsecured) configuration information.</param>
        /// <param name="secure">Contains non-public (secured) configuration information. 
        /// When using Microsoft Dynamics 365 for Outlook with Offline Access, 
        /// the secure string is not passed to a plug-in that executes while the client is offline.</param>
        public PostOperationcrd9a_carCreate(string unsecure, string secure)
            : base(typeof(PostOperationcrd9a_carCreate))
        {
            
           // TODO: Implement your custom configuration handling.
        }


        /// <summary>
        /// Main entry point for he business logic that the plug-in is to execute.
        /// </summary>
        /// <param name="localContext">The <see cref="LocalPluginContext"/> which contains the
        /// <see cref="IPluginExecutionContext"/>,
        /// <see cref="IOrganizationService"/>
        /// and <see cref="ITracingService"/>
        /// </param>
        /// <remarks>
        /// For improved performance, Microsoft Dynamics 365 caches plug-in instances.
        /// The plug-in's Execute method should be written to be stateless as the constructor
        /// is not called for every invocation of the plug-in. Also, multiple system threads
        /// could execute the plug-in at the same time. All per invocation state information
        /// is stored in the context. This means that you should not use global variables in plug-ins.
        /// </remarks>
        protected override void ExecuteCdsPlugin(ILocalPluginContext localContext)
        {
            if (localContext == null)
            {
                throw new InvalidPluginExecutionException(nameof(localContext));
            }           
            // Obtain the tracing service
            ITracingService tracingService = localContext.TracingService;

            try
            { 
                // Obtain the execution context from the service provider.  
                IPluginExecutionContext context = (IPluginExecutionContext)localContext.PluginExecutionContext;

                // Obtain the organization service reference for web service calls.  
                IOrganizationService service = localContext.CurrentUserService;

                // TODO: Implement your custom Plug-in business logic.
                // The InputParameters collection contains all the data passed in the message request.  
                if (context.InputParameters.Contains("Target") &&
                    context.InputParameters["Target"] is Entity)
                {
                    // Obtain the target entity from the input parameters.  
                    Entity entity = (Entity)context.InputParameters["Target"];

                    // Obtain the organization service reference which you will need for  
                    // web service calls.  
                    try
                    {
                        // Plug-in business logic goes here.  
                        // Create a task activity to follow up with the account customer in 7 days. 
                        Entity followup = new Entity("task");

                        followup["subject"] = "New car created";
                        followup["description"] =
                            "New car has been created. This task has been created by custom plug-in.";
                        followup["scheduledstart"] = DateTime.Now.AddDays(7);
                        followup["scheduledend"] = DateTime.Now.AddDays(7);
                        followup["category"] = context.PrimaryEntityName;

                        // Refer to the account in the task activity.
                        if (context.OutputParameters.Contains("id"))
                        {
                            Guid regardingobjectid = new Guid(context.OutputParameters["id"].ToString());
                            //change for account and verify if it works
                            string regardingobjectidType = "crd9a_car";

                            followup["regardingobjectid"] =
                            new EntityReference(regardingobjectidType, regardingobjectid);
                        }

                        // Create the task in Microsoft Dynamics CRM.
                        tracingService.Trace("FollowupPlugin: Creating the task activity.");
                        service.Create(followup);
                    }

                    catch (FaultException<OrganizationServiceFault> ex)
                    {
                        throw new InvalidPluginExecutionException("An error occurred in FollowUpPlugin.", ex);
                    }

                    catch (Exception ex)
                    {
                        tracingService.Trace("FollowUpPlugin: {0}", ex.ToString());
                        throw;
                    }
                }


            }	
            // Only throw an InvalidPluginExecutionException. Please Refer https://go.microsoft.com/fwlink/?linkid=2153829.
            catch (Exception ex)
            {
                tracingService?.Trace("An error occurred executing Plugin CreateTaskWhenEntityCreated.CreateTaskWhenEntityCreated.PostOperationcrd9a_carCreate : {0}", ex.ToString());
                throw new InvalidPluginExecutionException("An error occurred executing Plugin CreateTaskWhenEntityCreated.CreateTaskWhenEntityCreated.PostOperationcrd9a_carCreate .", ex);
            }	
        }
    }
}
